<body>
New map and/or configuration created <br /><br />
# Locations - <?php echo $this->numberLocations ?><br />
Vorname - <?php echo $this->user->firstName ?><br />
Nachname - <?php echo $this->user->lastName ?><br />
E-Mail Adresse - <?php echo $this->user->email ?><br />
Actioncode - <?php echo $this->actionCode ?><br />
URL - <?php echo 'http://'.$_SERVER['SERVER_NAME'].'/widgets/'.$this->user->email.'/production/example.html'?><br />
</body>
